### ISSUE TITLE
Continous control agent in plane with obstacles

### ISSUE THREAD

**Issue by wmkouw** [biaslab/RxAgents#1]
In this wonderful paper by [Huebotter et al.](https://arxiv.org/abs/2209.08033), they demonstrated an agent in a 2D planar environment that navigates to a setpoint, which, upon the agent reaching it, jumps to a new location. It's a bit like the old mobile game, Snake, but then in a continuous state-space with a continuous action-space.

I propose we build a similar agent but also add obstacles to this plane. We can use chance constraints (see also [#68](https://github.com/biaslab/RxInfer.jl/issues/68)) to indicate that the part of state-space the obstacle occupies, should not be traversed. The agent should find a trajectory around it.

The next step would be to learn the parameters of the chance constraints through interactions, i.e., the agent bumps into the obstacle and incurs a large prediction error.

**Comment by wmkouw** [comment]
Chengfeng implemented a ship control agent operating on a 2d plane, see folder `ship`.

Implementing obstacles, through for instance chance constraints, is still a todo.

**Comment by albertpod** [comment]
Hey @wmkouw @Chengfeng-Jia! Any developments on this one? I see the ETA is on May 18.

**Comment by Chengfeng-Jia** [comment]
Considering that Bart has already utilized NUV prior to making control decisions to avoid obstacles, I suggest perhaps closing this issue.
